- README.md
Add to the README for running an individual example from the root using turbo, so that the dependencies are built properly.
> docs: Add documentation for running an individual example.

- packages/gensx/tests/streaming.test.tsx
Fix flakey test that relys on timing.
> chore: Fix flakey streaming test.

- packages/create-gensx/package.json
- packages/gensx-openai/package.json
- packages/gensx/package.json
- pnpm-lock.yaml
Fix warning about `punycode`.
#121
> fix: Update vite-plugin-dts.

- docs/astro.config.mjs
- docs/src/content/docs/basic-concepts.mdx
- docs/src/content/docs/quickstart.mdx
- packages/create-gensx/src/templates/typescript/src/index.tsx.template
- Updates the quickstart
- adds a basic concepts doc that explains components, composition, execution, providers, etc
> docs: adding basic concepts doc and refactoring quickstart

- README.md
- examples/README.md
Updates the readme with feedback from #129 
Also adds an examples README
> docs: updating readme and adding examples readme

- docs/astro.config.mjs
- docs/src/content/docs/component-reference/openai.mdx
Adds in the reference for openai components. Also trying to land on a good layout for reference pages
> docs: adding openai component reference

- docs/src/content/docs/basic-concepts.mdx
- docs/src/content/docs/quickstart.mdx
Realized i had some issues with the docs where i had `StreamingComponent` rather than `StreamComponent`
> docs: fix docs on streaming

- .github/workflows/check-create-gensx-command.yml
- .github/workflows/release.yml
- packages/create-gensx/src/cli.ts
- packages/create-gensx/tests/package.test.ts
* Add a hashbang to the cli command, to be sure it is executed with node
* Add a daily test to be sure that the command always works
chore: fix release workflow
> fix: Fix create-gensx and add daily test

- .github/workflows/check-create-gensx-command.yml
Accidentally include `--yes` for these.
> fix: Remove unnecessary --yes command.

- .github/workflows/check-create-gensx-command.yml
- packages/gensx/src/checkpoint.ts
- packages/gensx/tests/checkpoint.test.tsx
- packages/gensx/tests/component.test.tsx
- packages/gensx/tests/secrets.test.tsx
- packages/gensx/tests/utils/executeWithCheckpoints.ts
Update the checkpoint persistence code to match the new API shape.
> feat: Update checkpoint call to match the new API shape.

- eslint.config.mjs
- examples/hackerNewsAnalyzer/.gitignore
- packages/create-gensx/src/index.ts
- packages/gensx/src/checkpoint.ts
Remove errant console.log and fix linting so it dosen't happen again.
> fix: Remove console.log and fix eslint.

- .github/workflows/test-examples.yml
- examples/gsxChatCompletion/index.tsx
Fixing the gsxChatCompletion example 
This was broken by my change in #242 but for some reason that PR got a green build.
I realized that the test_examples.yml build pipeline wasn't working correctly and was running only the code already in main. To improve this, i made the following updates:
- Makes examples run whenever a package is changed to check for breaking changes 
- Changes from `pull_request` to `pull_request_target` to make it easier to debug and fix issues. 
- Adds a clean step 
Note this PR will always fail because it's running both the old and new versions of the test_examples file.
> docs: fixing gsxChatCompletion example

- packages/create-gensx/src/templates/typescript/src/index.tsx.template
Update the project created with `create-gensx` to use `gsx.workflow.`
> fix: Update template project to use gsx.workflow.

- pnpm-lock.yaml
- website/docs/package.json
- website/docs/src/app/layout.tsx
- website/home/app/layout.tsx
- website/home/package.json
Added vercel analytics tags for docs and the website
> chore: Added vercel analytics to website and docs

- examples/gsxChatCompletion/index.tsx
- packages/gensx-openai/src/tools.tsx
- packages/gensx-openai/tests/tools.test.tsx
Rename tool.execute to tool.run and updating corresponding test/example
> feat: renaming tool.execute to tool.run

- packages/gensx-cli/src/commands/login.ts
- packages/gensx-cli/src/logger.ts
> feat: Colorize login command.

- packages/gensx-ai-sdk/.gitignore
- packages/gensx-ai-sdk/README.md
- packages/gensx-ai-sdk/eslint.config.mjs
- packages/gensx-ai-sdk/package.json
- packages/gensx-ai-sdk/src/index.tsx
- packages/gensx-ai-sdk/tests/index.test.tsx
- packages/gensx-ai-sdk/tsconfig.json
- packages/gensx-ai-sdk/vite.config.ts
- packages/gensx-ai-sdk/vitest.config.ts
- pnpm-lock.yaml
- release-please-config.json
Added support for main functions of the [AI SDK](https://sdk.vercel.ai/docs/reference/ai-sdk-core)
Example: 
``` jsx
import { google } from '@ai-sdk/google';
import { gsx } from "gensx";
import { GenerateText } from "./ai-sdk";
export const JokeTeller = gsx.Component<{ joke: string }, string>('JokeTeller', async ({ joke }) => {
const model = google('gemini-2.0-flash')
return (
<GenerateText
model={model}
prompt={joke}
>
{({ text }) => text}
</GenerateText>
)
})
```
> feat: new component package for ai sdk package support 

- packages/gensx-cli/src/commands/login.ts
- packages/gensx-cli/src/commands/new.ts
- packages/gensx-cli/src/index.ts
- packages/gensx-cli/src/utils/config.ts
- packages/gensx-cli/src/utils/terminal.ts
Ask the user to login when they run `gensx new` the first time. It only asks the first time, and stores some state in `~/.config/gensx/config` to ensure it does not happen on subsequent times.
```
gensx new ~/code/gensx-new-test
Welcome to GenSX! Let's get you set up first.
Press any key to open your browser and login to GenSX Cloud (ESC to skip)               
✔ Logging in to GenSX Cloud
✔ Opening https://app.gensx.com/auth/device/01JMJ7E2X49HQF8FCDBF1G3EMW?code_verifier=3qyw5fq73KhI3SkYhkRKg1WpNij4TFTbdYpWS0Squ9Q
✔ Successfully logged in to GenSX
✔ Loading available templates
✔ Loading template: TypeScript Project
✔ Creating project directory
✔ Copying template files
✔ Initializing npm project
✔ Installing dependencies
✔ Installing development dependencies
✔ Successfully created GenSX …
```
> feat: Prompt for login when calling new the first time.

- packages/gensx/src/component.ts
- packages/gensx/src/types.ts
- packages/gensx/tests/component.test.tsx
Fixes #327 
Add Component.run and StreamComponent.run, to make it simpler to call components inline.
> feat: Component.run

- .vscode/settings.json
- examples/self-modifying-code/README.md
- examples/self-modifying-code/agent/codeAgent.tsx
- examples/self-modifying-code/agent/smcAgent.tsx
- examples/self-modifying-code/agent/steps/generateGoalState.tsx
- examples/self-modifying-code/agent/steps/generatePlan.tsx
- examples/self-modifying-code/agent/tools/bashTool.tsx
- examples/self-modifying-code/agent/tools/buildTool.tsx
- examples/self-modifying-code/agent/tools/editTool.tsx
- examples/self-modifying-code/agent_context.json
- examples/self-modifying-code/eslint.config.mjs
- examples/self-modifying-code/index.tsx
- examples/self-modifying-code/nodemon.json
- examples/self-modifying-code/package.json
- examples/self-modifying-code/tsconfig.json
- examples/self-modifying-code/workspace.tsx
- packages/gensx-openai/tests/gsx-completion.test.tsx
- pnpm-lock.yaml
This example demonstrates a self-modifying code agent. The agent:
1. Creates a copy of it's source code
2. Reads context about previous operations
3. Decides on a goal state
4. Modifies it's source code to match the goal state
5. Runs tests to verify the changes
6. Starts a new version of itself to continue the work
7. Spins itself down and allows the new agent to take control
> docs: adding the self-modifying-code example

- examples/open-router/README.md
- examples/open-router/eslint.config.mjs
- examples/open-router/nodemon.json
- examples/open-router/package-lock.json
- examples/open-router/package.json
- examples/open-router/src/index.tsx
- examples/open-router/tsconfig.json
- pnpm-lock.yaml
- website/docs/src/content/component-reference/openai.mdx
- website/docs/src/content/component-reference/openrouter.mdx
Added example showing how to use OpenRouter. It's a simple example that uses the OpenAI provider and a simple option through the provider prop.
> docs: Add open router example

- website/home/components/markdown-to-html.tsx
> docs: Remove corners from code blocks and images

- .release-please-manifest.json
> chore: Fix release-please manifest.

- release-please-config.json
Force release of all the packages.
> fix: Force release.

- release-please-config.json
> fix: Force release of core.

- packages/create-gensx/package.json
- packages/gensx-anthropic/package.json
- packages/gensx-cli/package.json
- packages/gensx-core/package.json
- packages/gensx-mcp/package.json
- packages/gensx-openai/package.json
- packages/gensx-vercel-ai-sdk/package.json
- packages/gensx/package.json
Try to force a new version for all packages.
> fix: Force release for all packages.

- .github/workflows/release-cli-binary.yml
- .github/workflows/release.yml
Fix how we extract the version when publishing to homebrew.
> fix: Fix the version extraction when publishing to homebrew.

- website/home/_posts/why-react-is-the-best-backend-workflow-engine.md
- website/home/app/blog/[slug]/page.tsx
- website/home/components/markdown-to-html.tsx
> docs: (blog) Why react is suprisingly the best model for backend workflow

- website/home/_posts/why-react-is-the-best-backend-workflow-engine.md
switching list items from italics to bold
> docs: updating list items to bold in react blog

- examples/all-models-metadata/README.md
- examples/all-models-metadata/eslint.config.mjs
- examples/all-models-metadata/nodemon.json
- examples/all-models-metadata/package-lock.json
- examples/all-models-metadata/package.json
- examples/all-models-metadata/src/index.tsx
- examples/all-models-metadata/tsconfig.json
- pnpm-lock.yaml
Example that uses the open router models endpoint to get pricing and other metadata for models across providers
> docs: Add example to pull model metadata

- website/home/components/nav.tsx
Fix broken link for the blog on mobile.
> docs: fix mobile blog link

- website/home/app/overview/page.tsx
- website/home/next.config.ts
Remove the overview stub page and handle the redirect via next config.
> docs: fix overview redirect

- website/docs/src/content/component-reference/anthropic.mdx
adding max_tokens in all anthropic example docs since it's a required parameter
> docs: adding max_tokens in the anthropic docs

- packages/gensx/src/templates/projects/typescript/.cursor/gensx-ai-sdk.mdc
- packages/gensx/src/templates/projects/typescript/.cursor/gensx-anthropic.mdc
- packages/gensx/src/templates/projects/typescript/.cursor/gensx-mcp.mdc
- packages/gensx/src/templates/projects/typescript/.cursor/gensx-openai.mdc
- packages/gensx/src/templates/projects/typescript/.cursor/gensx.mdc
- website/docs/src/content/component-reference/anthropic.mdx
- website/docs/src/content/component-reference/openai.mdx
- website/docs/src/content/component-reference/vercel-ai.mdx
- Fixing syntax and other typos in cursor rules
- Adds a tool example
- Adds details on using the openai provider with openai compatible apis
- Also fixed a couple of docs
> fix: small fixes and updates to cursor rules

- pnpm-lock.yaml
- website/docs/package.json
- website/docs/src/app/layout.tsx
- website/home/app/layout.tsx
- website/home/package.json
Add Google analytics to home/docs. We are hoping that this helps with our Google Search indexing issues.
https://nextjs.org/docs/messages/next-script-for-ga
> feat: Add Google Analytics to home and docs.

- .vercelignore
I noticed that we are deploying the websites whenever we create new releases. This should solve that, by ignoring changes to those files.
> chore: Don't create new webiste releases when packages are released or updated.

- website/docs/src/content/patterns/tools.mdx
Adds a simple patterns docs showing how to use tools in GenSX.
> docs: adding patterns docs for tools

- examples/groq-deepseek-r1-distilled/README.md
- examples/reflection/reflection.tsx
- website/docs/src/content/basic-concepts.mdx
- website/docs/src/content/component-reference/anthropic.mdx
- website/docs/src/content/component-reference/mcp.mdx
- website/docs/src/content/component-reference/openai.mdx
- website/docs/src/content/component-reference/vercel-ai.mdx
- website/docs/src/content/concepts/how-gensx-works.mdx
- website/docs/src/content/patterns/reflection.mdx
- Adds light docs on component.run
- Updates reflection example and page to use component.run
- Updates reference docs to not use gensx.execute
> docs: documenting component.run

- packages/gensx/package.json
- packages/gensx/src/commands/login.ts
- packages/gensx/src/commands/new.ts
- packages/gensx/src/utils/exec.ts
- packages/gensx/tests/commands/login.test.ts
- packages/gensx/tests/commands/new.test.ts
- packages/gensx/tsconfig.json
- packages/gensx/vitest.config.ts
Add tests for the login flow and some more interactivity.
> test: Tests for login and interactivity.

- packages/gensx/package.json
- pnpm-lock.yaml
Add tslib dependency for the build command.
> fix: Add tslib dependency.

- packages/gensx-openai/__mocks__/openai.ts
- packages/gensx-openai/src/openai.tsx
- packages/gensx-openai/src/structured-output.tsx
- packages/gensx/src/commands/run.ts
- removes `run` from the url path for running a workflow
- updates status to executionStatus
- removes stderror and stdout
> fix: updating cli to match with new api shape

- containers/builder/build_container.sh
- packages/gensx/src/utils/bundler.ts
Update docker namespace to use `gensx` instead of `gensxeng`.
> fix: Update docker namespace.

- packages/gensx-storage/src/database/filesystem.ts
- packages/gensx-storage/tests/database/filesystem.test.ts
- packages/gensx-storage/tests/database/remote.test.ts
- Adds better test coverage for DatabaseProvider and useDatabase
- Fixes bug in the filesystem implementation of db.batch
> fix: fixing bug in db.batch() for filesystem and adding tests

- packages/gensx-storage/README.md
updating the readme to include database and search and fix some existing issues
> chore: updating readme for @gensx/storage

- packages/gensx/src/commands/deploy.ts
Direct the user to the right place after deployments.
> fix: Use the right URL after deployments.

- packages/gensx-cloud-mcp/README.md
- packages/gensx-cloud-mcp/src/index.tsx
- website/docs/src/content/cloud/mcp-server.mdx
- website/docs/src/content/cloud/storage/search.mdx
- website/home/public/llms-full.txt
- update mcp to remove input wrapper when running workflows
- improve mcp docs
- remove incorrect hybrid search example
> feat: mix fixes to mcp server, docs, etc

- website/docs/src/content/component-reference/storage-components/blob-reference.mdx
- website/docs/src/content/component-reference/storage-components/database-reference.mdx
- website/docs/src/content/component-reference/storage-components/search-reference.mdx
updating reference docs to latest format with pagination
> docs: updating pagination docs for storage

- packages/create-gensx/tests/index.test.ts
- packages/gensx/src/commands/new.ts
- packages/gensx/src/templates/projects/typescript/README.md.template
- packages/gensx/src/templates/projects/typescript/package.json.template
- packages/gensx/src/templates/projects/typescript/src/index.tsx.template
- packages/gensx/src/templates/projects/typescript/src/workflows.tsx.template
- Updates project to be deployable (main code is in workflow.tsx with a short script in index.tsx)
- Updated commands to support `dev` (run locally), `start` (run the dev server), and `deploy` (deploy to gensx cloud)
- Basic renaming to change the workflow from `Respond` to `Chat` (makes for a better api name)
- Updated readme to have an overview of deploying and running locally
Fixes #586
> feat: updating template project to be deployable

- packages/gensx/src/index.ts
Remove the gating for the `deploy` commands and others.
https://discord.com/channels/1332417959032782908/1332417959473451071/1366803429590306846
> fix: Remove gating for deploy/environment/etc.

- examples/chat-memory/README.md
- examples/chat-memory/package.json
- examples/rag/package.json
- examples/text-to-sql/package.json
- pnpm-lock.yaml
updating to the latest version of storage packages
> chore: updating package versions for storage examples

- examples/rag/src/initialize.tsx
- examples/rag/src/workflows.tsx
- packages/gensx/src/utils/schema.ts
> fix: fixing but with schema detection only using main file

- website/docs/src/content/cli-reference/deploy.mdx
- website/docs/src/content/cli-reference/run.mdx
- website/docs/src/content/component-reference/storage-components/blob-reference.mdx
- website/docs/src/content/component-reference/storage-components/database-reference.mdx
- website/docs/src/content/component-reference/storage-components/search-reference.mdx
- adds docs for project/environment params in CLI
- documenting --yes param
> docs: documenting updates to storage and cli

- packages/gensx-storage/src/blob/filesystem.ts
- packages/gensx-storage/src/blob/remote.ts
- packages/gensx-storage/src/blob/types.ts
- packages/gensx-storage/tests/blob/filesystem.test.ts
- packages/gensx-storage/tests/blob/remote.test.ts
- website/docs/src/content/component-reference/storage-components/blob-reference.mdx
Updates the listBlobs method to return both lastModified and size, matching the latest api shape
> feat: updating listblobs to return extra metadata

- packages/gensx/src/commands/start.tsx
- packages/gensx/tests/commands/start.test.ts
- fixes issue where schema wasn't being written properly
- fixes issues where tsconfigs needed to have `rootDir: "."` in them
- Adds tests and reduced mocking
> fix: fixing bug writing and finding build files in start command

- examples/anthropic-examples/package.json
- examples/blog-writer/package.json
- examples/chat-memory/package.json
- examples/hacker-news-analyzer/nodemon.json
- examples/hacker-news-analyzer/package.json
- examples/openai-examples/package.json
- examples/rag/package.json
- examples/text-to-sql/package.json
- examples/vercel-ai/package.json
- examples/vercel-ai/src/index.ts
- examples/vercel-ai/src/workflows.ts
- packages/gensx-core/package.json
- packages/gensx-core/src/component.ts
- packages/gensx-core/src/context.ts
- packages/gensx-core/src/types.ts
- packages/gensx-core/src/wrap.ts
- packages/gensx-core/tests/component.test.ts
- packages/gensx-core/tests/secrets.test.ts
- packages/gensx-core/tests/utils/executeWithCheckpoints.ts
- packages/gensx-core/tests/wrap.test.ts
- packages/gensx-openai/src/openai.ts
- packages/gensx-openai/tests/openai.test.ts
- packages/gensx-vercel-ai/package.json
- packages/gensx-vercel-ai/src/index.ts
- packages/gensx-vercel-ai/tests/index.test.ts
- pnpm-lock.yaml
Add support to capture the output from streaming components. Also get the improvement of intermediate output, which we did not have before.
https://github.com/user-attachments/assets/1b400c1e-8cc0-4da4-b9cc-0260d3739814
> feat: Record output for streaming components

- examples/all-models-metadata/package.json
- examples/anthropic-examples/package.json
- examples/blog-writer/package.json
- examples/chat-memory/package.json
- examples/deep-research/package.json
- examples/groq-deepseek/package.json
- examples/hacker-news-analyzer/package.json
- examples/open-router/package.json
- examples/openai-examples/package.json
- examples/openai-examples/src/workflows.ts
- examples/rag/package.json
- examples/rag/src/initialize.ts
- examples/reflection/package.json
- examples/text-to-sql/package.json
- examples/text-to-sql/tsconfig.json
- examples/vercel-ai/package.json
- packages/gensx/src/dev-server.ts
- packages/gensx/src/utils/schema.ts
- packages/gensx/tests/dev-server.test.ts
- packages/gensx/tests/utils/schema.test.ts
- pnpm-lock.yaml
- release-please-config.json
- updates schema detection logic to not depend on decorators
- updates examples to point to non-alpha package versions
- a couple other small fixes in examples
- also fixes the dev server
> fix: updating schema detection for v2 programming model

- packages/gensx/src/templates/projects/typescript/src/workflows.ts.template
- packages/gensx/src/templates/projects/typescript/template.json
- packages/gensx/tests/commands/deploy.test.ts
also made a small change to inline the model with the vercel ai sdk
> feat: upgrading template from alpha to stable package versions

- eslint.config.mjs
- packages/gensx/tests/commands/deploy.test.ts
- updating deploy tests to fix flakey issue due to config file being overwritten
- adding eslint setting to make linting faster
> chore: improving flakiness of deploy tests and updating eslint

- examples/hacker-news-analyzer/package.json
- examples/hacker-news-analyzer/src/workflows.ts
- pnpm-lock.yaml
Update the HN analyzer example to use the `emitProgress` api.
> feat: Update HN example to use emitProgress.

- packages/gensx-core/src/component.ts
- packages/gensx-core/src/context.ts
- packages/gensx-core/src/index.ts
- packages/gensx-core/src/request-input.ts
- packages/gensx-core/src/workflow-context.ts
- packages/gensx-core/tests/request-input.test.ts
- packages/gensx-core/tests/workflow-context.test.ts
Change the name from `waitForInput` to `requestInput`. The current name is just not right, and leaks some implementation details into the name.
> feat: Update name from waitForInput to requestInput.

- examples/draft-pad/package.json
- pnpm-lock.yaml
Move to react 19 types to fix dependencies across monorepo
> fix: move to react 19 types

- packages/gensx-core/src/workflow-state.ts
- packages/gensx-core/tests/workflow-state.test.ts
- packages/gensx-react/package.json
- packages/gensx-react/src/hooks/use-gensx.ts
- packages/gensx-react/src/hooks/use-object.ts
- packages/gensx-react/src/index.ts
- pnpm-lock.yaml
Ensure that we appropriately clone objects before mutating them.
> fix: Avoid duplication issue due to object mutation.

- .github/workflows/release.yml
- packages/gensx/src/commands/headless-deploy.ts
- packages/gensx/src/index.ts
- packages/gensx/tests/commands/deploy-headless.test.ts
- packages/gensx/tests/commands/deploy.test.ts
Add support for non-interactive deploys.
> feat: Support non-interactive deploys.

- packages/gensx/src/commands/headless-deploy.ts
- packages/gensx/src/index.ts
- packages/gensx/src/models/environment.ts
- packages/gensx/src/models/projects.ts
Pipethrough tokens where needed for headless deploy.
> fix: Fix auth for headless deploy

- .github/workflows/sync-templates.yml
POC for syncing showcase examples with separate template repos. 
Just trying to get deep research working with this repo: https://github.com/gensx-inc/deep-research-template
> chore: poc for syncing templates

- examples/deep-research/README.md
adding "use this template" button
> chore: testing repo sync

- .github/workflows/build-example-workflows.yml
- .github/workflows/deploy-example-workflows.yml
- Add action for building example workflows on PR
- Fix path filters to match the right thing.
> feat: Add action for building examples on PR.

- .github/workflows/build-example-workflows.yml
- .github/workflows/deploy-example-workflows.yml
Use the github actions to build/deploy all the examples if there is a change.
> feat: Build/deploy all the examples.

- examples/client-side-tools/app/page.tsx
The `mapMove` tool was not working for desktop view.
> fix: Fix map move not working for some cases.

- website/home/app/showcase/showcase-client.tsx
* Update links for the demos in the showcase
* Add the map demo to the showcase
> feat: Update showcase

- .github/workflows/deploy-example-workflows.yml
Use separate jobs with the right environment variables for deploying examples in CI.
> fix: Break apart deploy workflow jobs.

- examples/self-modifying-code/package.json
- packages/gensx-vercel-ai/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
upgrading to later version of zod required by latest vercel ai packages
> fix: updating packages to use newer zod version
