gensx-inc/gensx

docs/src/content/docs/overview.mdx
docs/src/content/docs/why-jsx.mdx

A few minor changes to the docs to fix typos, make perspective consistent, and add in contractions to make the writing easier to read.

fix: fixing typos and other small doc improvements

---

docs/src/content/docs/index.mdx

Updated the background to have a dot pattern

docs: Add dot background pattern to landing page

---

examples/blogWriter/README.md
examples/hackerNewsAnalyzer/README.md
examples/streaming/README.md

Adding in instructions to set OpenAI API Key in examples

fix: add in missing instruction to examples

---

examples/hackerNewsAnalyzer/hackerNewsAnalyzer.tsx
examples/hackerNewsAnalyzer/hn.ts
packages/gensx/package.json
packages/gensx/src/checkpoint.ts
packages/gensx/src/component.ts
packages/gensx/src/context.ts
packages/gensx/src/resolve.ts
packages/gensx/src/workflow-context.ts
packages/gensx/tests/checkpoint.test.tsx

Checkpoint implementation with tests. 
6/7 items for https://github.com/cortexclick/gensx/issues/136 - just need to add support for streaming components (will require some care to fork the stream and make sure we don't block - will do this separately). 
Important bits here: 
- checkpointing is hidden behind an env var `GENSX_CHECKPOINTS` and is off by default
- Care is taken to minimize chattiness with the server via a "queue". We only ever process one checkpoint at a time. Processing checkpoints is non-blocking. We drop "intermediate" checkpoints if we have a "fresh" checkpoint in the queue. There is not really a queue, nor a concept of "fresh checkpoints" - but this is the best analogy. 
- Parent ID is maintained throughout execution via context to ensure nodes are parented properly. …

feat: Add checkpointing

---

examples/blogWriter/README.md
examples/blogWriter/package.json
examples/hackerNewsAnalyzer/README.md
examples/hackerNewsAnalyzer/package.json
examples/reflection/README.md
examples/reflection/package.json
examples/streaming/README.md
examples/streaming/package.json
examples/structuredOutputs/README.md
examples/structuredOutputs/package.json

Updating all examples to use `start` instead of `run`. This aligns the examples with the output of `create gensx` and prevents the weirdness of `npm run run`

style: updating all examples to use "start" instead of "run"

---

README.md
docs/src/content/docs/basic-concepts.mdx
docs/src/content/docs/concepts/providers.mdx
examples/README.md
examples/blogWriter/package.json
examples/hackerNewsAnalyzer/package.json
examples/providers/README.md
examples/providers/eslint.config.mjs
examples/providers/firecrawlProvider.tsx
examples/providers/index.tsx
examples/providers/nodemon.json
examples/providers/package.json
examples/providers/tsconfig.json
examples/reflection/package.json
examples/structuredOutputs/package.json
pnpm-lock.yaml

Recreating #148 from a clean branch
Adds the concept doc for providers
Also adds a provider example that shows how to create a provider for Firecrawl (that is discussed in the doc)
It's worth noting that the top of this doc is the same as the text from the basic concepts page but it extends the info. Eventually we will also want an "Available Providers" section but when written currently, it only contains the OpenAIProvider.

docs: adding docs and example on providers

---

packages/gensx/src/checkpoint.ts
packages/gensx/src/component.ts
packages/gensx/tests/checkpoint.test.tsx

Adds support for checkpointing within `StreamComponent`. Special care is taken to fork the stream so that we don't block. When the user reads the stream, we follow along, accumulate the value, and then send the final `completeNode` call with the complete value at the end. 
Fixes https://github.com/cortexclick/gensx/issues/142 fixes https://github.com/cortexclick/gensx/issues/136

feat: Add checkpoint support for StreamComponent

---

packages/gensx/src/array.ts
packages/gensx/src/index.ts
packages/gensx/tests/array.test.tsx

Adds a new `gsx.array` wrapper that exposes a fluent API for array operations over array elements that may contain components that need to be executed before execution. 
Fixes https://github.com/cortexclick/gensx/issues/150 fixes https://github.com/cortexclick/gensx/issues/107
Due to typescript type limitations, many of these methods do require a generic parameter that maps to the operations output type. Something we can fix up in the future via compiler extensions and IDE integration. 
An example: 
```tsx
const arr = gsx.array<NumberWrapperOutput>([
<NumberWrapper n={1} />,
<NumberWrapper n={2} />,
<NumberWrapper n={3} />,
<NumberWrapper n={4} />,
<NumberWrapper n={5} />,
]);
const result = await arr
.map<number>(n => <NumberDoubler value={n.value} />)
.map<number>(n => <Value value={n} …
```

feat: Add `gsx.array` plus `map`, `filter`, `reduce`, and `flatMap`

---

packages/gensx/src/checkpoint.ts
packages/gensx/src/component.ts
packages/gensx/tests/checkpoint.test.tsx

The full graph is executed in parallel. This means that `addNode` calls don't necessarily occur in order, though usually they do. Luckily the context of the `parentId` is maintained correctly all the way through the execution tree.
The result is nodes that occassionally get dropped from the execution graph.
@danfhernandez was occasionally seeing instances where the first component was dropped from the checkpoint. I observed this once myself as well:
This change adds support for handling out of order insertion of nodes into the graph. If we try to insert a node with a parentId into the graph but the parent hasn't arrived yet, then we put it into an `orphaned` nodes list, and attempt to process it on subsequent `addNode` calls when other nodes arrive. In addition, we never write out a …

fix: Fix checkpoint race condition by handling out of order arrival of nodes

---

packages/gensx/src/array.ts
packages/gensx/tests/array.test.tsx

Fixes #171 
Adds support so that you can pass in objects like a `string[]` to `gsx.array()`

feat: adding support for generic arrays in gsx.array

---

.github/actions/create-release-candidate/action.yml
.github/settings.yml
README.md
docs/astro.config.mjs
docs/src/content/docs/examples/blog-writing.mdx
docs/src/content/docs/examples/hn.mdx
docs/src/content/docs/index.mdx
docs/src/content/docs/patterns/structured-outputs.mdx
docs/src/content/docs/quickstart.mdx
packages/create-gensx/CHANGELOG.md
packages/gensx-openai/CHANGELOG.md
packages/gensx-openai/README.md
packages/gensx/CHANGELOG.md
packages/gensx/README.md

Just a big rename PR for the most part. Adds discord links to the readme, header, and landing page as well:

docs: add discord links and update github links

---

packages/gensx-openai/src/index.tsx
packages/gensx/src/checkpoint.ts
packages/gensx/src/component.ts
packages/gensx/src/index.ts
packages/gensx/src/types.ts
packages/gensx/tests/checkpoint.test.tsx
packages/gensx/tests/secrets.test.tsx

This feature adds secrets masking to enable users to replace sensitive values in the checkpoint with a `[secret]` mask.
Fixes https://github.com/gensx-inc/gensx/issues/156
- Add new `ComponentOpts` type
- Add support for selective or broad masking of props via property paths.
- Support broad masking of outputs via the "output" property path. 
- Support Components and StreamComponent
- Support transitive secrets masking across children
- Extensive tests (16 cases, 700 lines) across all the edge cases I could think of
Secrets can be masked by adding props property paths, or the "output" key to a new `ComponentOpts.secrets` array. 
Masked secrets are tracked by value, masking is transitive across children, and we search props and outputs to mask any value even if it just contains the masked …

feat: Add secrets masking

---

packages/gensx/src/types.ts
packages/gensx/tests/streaming.test.tsx

StreamComponent type inference was broken for nesting: 
```tsx
<ChatCompletion stream={true}>
{ (result) => {...}} // result is implicitly any...
</ChatCompletion>
```
This change improves the typing so that when `stream=false` result is automatically inferred as string, and when `stream=true` it is inferred as Streamable. 
Added tests that do nothing more than exercise the typescript compiler for this path. 
Fixes https://github.com/gensx-inc/gensx/issues/195

fix: Fix stream component type inference in child functions

---

packages/gensx-openai/src/index.tsx

This didn't get fixed during the refactor, but somehow the builds on PR and release both passed...

fix: update secret component opts for openAI provider

---

packages/create-gensx/vite.config.ts
packages/gensx-openai/vite.config.ts
packages/gensx/vite.config.ts

Due to surprising default behavior with vite-plugin-dts (https://github.com/qmhc/vite-plugin-dts/issues/322), Typescript compile errors were not failing the build, allowing broken packages to be published.

chore: Throw errors if there are typescript compile errors during build.

---

packages/gensx/src/component.ts
packages/gensx/src/types.ts
packages/gensx/tests/component.test.tsx

Fixes #187 
Allows you to rename components at invocation
```tsx
const response = await gsx.execute<string>(
<OpenAIProvider
apiKey={process.env.OPENAI_API_KEY}
componentOpts={{ name: "DerekOpenAI" }}
>
<ChatCompletion
model="gpt-4o"
messages={[{ role: "user", content: "Hello" }]}
componentOpts={{ name: "DerekChat" }}
/>
</OpenAIProvider>,
);
console.log(response);
```

feat: adding the ability to rename components via componentOpts

---

packages/gensx/src/component.ts
packages/gensx/src/context.ts
packages/gensx/src/jsx-runtime.ts
packages/gensx/src/resolve.ts
packages/gensx/tests/component.test.tsx
packages/gensx/tests/jsx-runtime.test.tsx

Fixes https://github.com/gensx-inc/gensx/issues/226
The root cause of that bug is passing props from a parent component to a child that runs via `gsx.execute`: 
```tsx
const Parent = gsx.Component("Parent", (props) => {
// boom - this blows up because child is unexpectedly receiving `props.children`
gsx.execute(<Child ...props/>);
return { somethingElse }
}
```
This change fixes that with a few changes: 
- separate out children from the rest of props before a component function gets called/executed
- rework the parentID execution context flow to make sure that checkpointing and provider context continues to flow as expected
Testing: 
- Added a test to make sure that a component's function does not receive `props.children`
- Fixed an errant component renaming test that was trying to render …

fix: Separate `children` from other props before component execution

---

packages/gensx/src/checkpoint.ts
packages/gensx/src/component.ts
packages/gensx/src/context.ts
packages/gensx/src/jsx-runtime.ts
packages/gensx/src/resolve.ts
packages/gensx/tests/checkpoint.test.tsx
packages/gensx/tests/component.test.tsx

Sorry for the vague title but this change does three semi-related things: 
1. Makes sure that any `asyncIterable` is preserved during resolution. This is done in addition to the standard `Streamable` guard. This is necessary for cases where a component returns something like a raw OpenAI streaming chat completion result.
2. Mask functions and native functions from the checkpoint. This was previously failing whenever we tried to deep clone props/outputs that contained functions.
3. Ensure that deep resolution only executes framework functions, and not functions that might be appended to an object returned by the user.
I added tests covering all three changes. 
(3) is the meatiest and largest portion of this change. A demonstrative example: 
```tsx
const ComponentWithFunctions = …
```

fix: various fixes for handling of functions and streams during resolution and checkpointing

---

README.md
docs/astro.config.mjs
docs/src/content/docs/basic-concepts.mdx
examples/contexts/README.md
examples/groq-deepseek-r1-distilled/README.md
examples/groq-deepseek-r1-distilled/package.json
examples/structuredOutputs/README.md
packages/create-gensx/README.md
packages/create-gensx/src/templates/typescript/README.md.template

Replacing all references of gensx.dev to gensx.com

docs: updating references to gensx.com

---

website/home/next.config.ts

Currently running into an issue where the redirect to the docs site isn't working properly. I've set up a replicated environment to test the config and it's working but when pushing to vercel via the gensx repo/vercel account, there's a 404. 
Here's the docs I've followed to set this up: https://nextjs.org/docs/pages/building-your-application/deploying/multi-zones. 
That said, I can see the preview is working on this PR so that is promising.

chore: hardcoding docs url to see if it works

---

examples/gsxChatCompletion/index.tsx
packages/gensx-openai/src/gsx-completion.tsx
packages/gensx-openai/src/index.tsx
packages/gensx-openai/src/tools.tsx
packages/gensx-openai/tests/tools.test.tsx

Adds support so `GSXChatCompletion` returns the full array of messages including tool calls. This allows users to continue the conversation (with context) and see the tools that were called and their responses. 
**Important** - this PR only addresses non-streaming use cases.

feat: make GSXChatCompletion return the entire messages array. 

---

website/home/app/page.tsx

Updates examples for the home page

docs: updating examples on the home page

---

packages/gensx-cli/src/commands/login.ts

Node v18 does not have a global `crypto`, so make sure we import the things we need.

fix: Don't use global crypto.

---

packages/gensx/package.json
packages/gensx/src/component.ts
packages/gensx/src/execute.ts
packages/gensx/tests/checkpoint.test.tsx
packages/gensx/tests/utils/executeWithCheckpoints.ts
pnpm-lock.yaml

Add better handling for errors that are thrown when executing a workflow. The `gsx.Workflow` handler now ensures that checkpoints are still sent if the workflow errors, and the error is serialized into a consumable format when sent as part of the checkpoint.

feat: Handle errors when executing workflow

---

packages/gensx-vercel-ai-sdk/src/index.tsx
packages/gensx/src/component.ts
packages/gensx/src/execute.ts
packages/gensx/tests/execute.test.tsx

Fixes #325 
Constrain prop types to be an object, since that is the only thing that makes sense for JSX.

fix: Constrain prop types to be an object

---

examples/gsxChatCompletion/index.tsx
packages/gensx-openai/src/stream.tsx
packages/gensx-openai/src/structured-output.tsx
packages/gensx-openai/src/tools.tsx
packages/gensx-openai/tests/tools.test.tsx

Fixes #326
Specifically:
- Adds support for structured outputs to work with tools
- Adds a test for structured output with test
- Removes a couple of unnecessary params from toolExcecutor
- Fixes a couple of places where `ToolExecutor` was still showing in the trace.
- fixes some typos in examples
- Adds a structured output example with tool calls
- remove's `toolExecutorImpl`'s dependency on context since all it was doing was checking for context again

fix: making structured outputs work with tools

---

examples/providers/firecrawlProvider.tsx
website/docs/src/content/concepts/context.mdx

Fixes #335 
- Updates the `FirecrawlProvider` component to use `secretProps` in the option bag with the `apiKey` property.
- Updates the docs to discuss hiding secrets in providers.

docs: updating firecrawl example to hide secret

---

package.json
pnpm-lock.yaml
website/docs/.gitignore
website/docs/.npmrc
website/docs/next-sitemap.config.js
website/docs/package.json
website/home/.gitignore
website/home/.npmrc
website/home/next-sitemap.config.js
website/home/package.json

Fixes #296 
This generates sitemaps post-build and places them in the `public` directory.
There is a set of sitemaps generated for `docs`, and sitemapes generated for `home`, and the `home` sitemaps are setup to reference the docs sitemap.
Here is examples of the generated sitemaps:
home/public/sitemap.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<sitemap><loc>https://gensx.com/sitemap-0.xml</loc></sitemap>
<sitemap><loc>https://gensx.com/docs/sitemap.xml</loc></sitemap>
</sitemapindex>
```
home/public/sitemap-0.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" …
```

feat: Add sitemap for home/docs.

---

website/docs/next-sitemap.config.js

Fix the docs sitemap have `/docs/docs` in the paths.

fix: Fix duplicate /docs in docs sitemap path.

---

website/home/_posts/self-modifying-code.md
website/home/app/blog/[slug]/page.tsx
website/home/components/markdown-to-html.tsx
website/home/package-lock.json
website/home/tailwind.config.ts

docs: Updated blog styling

---

examples/salty-ocean-model-comparison/eslint.config.mjs
examples/salty-ocean-model-comparison/nodemon.json
examples/salty-ocean-model-comparison/package.json
examples/salty-ocean-model-comparison/src/index.tsx
examples/salty-ocean-model-comparison/tsconfig.json

When pushing the salty ocean example I introduced a build issue with prettier on that example.

docs: fix build issue with example

---

examples/mcp/README.md
packages/gensx-mcp/package.json
website/docs/src/content/examples/mcp.mdx

Fix a typo in the README/docs.

fix: Fix typo in MCP example title.

---

packages/gensx-core/src/execute.ts
packages/gensx-core/tests/execute.test.tsx

adds a `workflowName` param so when someone runs a workflow they can set a custom name: `myWorkflow.run({}, {workflowName: "new name})`

feat: adding support for a workflowName

---

.github/workflows/release.yml

Use the correct version variable when generating the homebrew formula.

fix: Use the right version when updating homebrew.

---

website/home/app/overview/page.tsx

Currently overview is indexed by google and navigates to a blank page so adding a redirect to docs.

docs: Add redirect for overview

---

website/home/next.config.ts

Redirect was going to the vercel builtin URL, so remove the url prefix to route correctly to the prod domain.

docs: fix overview redirect

---

packages/gensx-anthropic/src/gsx-completion.tsx
packages/gensx-anthropic/src/index.tsx
packages/gensx-anthropic/src/stream.tsx
packages/gensx-anthropic/src/structured-output.tsx
packages/gensx-anthropic/src/tools.tsx
packages/gensx-anthropic/tests/streaming-tools.test.tsx
packages/gensx-anthropic/tests/structured-output.test.tsx
packages/gensx-core/src/index.ts
packages/gensx-core/src/types.ts
packages/gensx-mcp/src/wrappers.ts
packages/gensx-openai/src/gsx-completion.tsx
packages/gensx-openai/src/index.tsx
packages/gensx-openai/src/stream.tsx
packages/gensx-openai/src/structured-output.tsx
packages/gensx-openai/src/tools.tsx
packages/gensx-openai/tests/tools.test.tsx

renaming `GSXToolParams` to `GSXToolProps` to be consistent with other input type names

fix: renaming gsxtoolparams to gsxtoolprops

---

website/home/app/layout.tsx

Fixing a placeholder. Saw this when I pasted a link into a discord I'm in:

docs: fix meta description

---

.github/workflows/release-cli-binary.yml
package.json
packages/gensx-claude-md/scripts/postinstall.js
packages/gensx-cli/.gitignore
packages/gensx-cli/deno.json
packages/gensx-cli/package.json
packages/gensx-cline-rules/scripts/postinstall.js
packages/gensx-cursor-rules/scripts/postinstall.js
packages/gensx-windsurf-rules/scripts/postinstall.js
packages/gensx/eslint.config.mjs
packages/gensx/package.json
packages/gensx/src/commands/build.ts
packages/gensx/src/utils/schema.ts
pnpm-lock.yaml
pnpm-workspace.yaml

* Fix cli binary build and add test
Fix resolution of named Props and structured output when bundling a workflow and producing the schema. There was a bug that was returning `{ "type": "object" }` for any output type that was not a `string` or `Streamable`, and there was an issue resolving named types for props. This resolved both of those problems.

fix: Fix schema extraction for structured types

---

packages/gensx-anthropic/package.json
packages/gensx-core/package.json
packages/gensx-mcp/package.json
packages/gensx-openai/package.json
packages/gensx-vercel-ai-sdk/package.json
pnpm-lock.yaml

Use peer dependencies more widely to fix multiple version issues. Fixes #490 . That issue is caused by there being multiple versions of `@gensx/core` at one time, and each version having its own notion of `Symbol.from`, so the context is not shared appropriately.

fix: Switch to peer dependencies.

---

packages/create-gensx/package.json
packages/gensx/src/commands/new.ts
pnpm-lock.yaml

Switch to use a regular select instead of a multiselect for installing AI assistant rules. The multiselect had surprising behavior because you needed to use spacebar to select.
Fix #503

fix: Use select instead of multiselect for selecting AI assistant rules.

---

packages/gensx/src/utils/config.ts

Fix up how we resolve the base urls to use, so that we always use the ones provided in env if provided.

fix: Ensure we are respecting the env vars for app/api base urls properly.

---

packages/gensx/src/commands/login.ts
packages/gensx/src/utils/config.ts

Fix #517 
Fallback to the default API url if no env var is provided. This was likely introduced in https://github.com/gensx-inc/gensx/pull/507
I will follow up with tests in another PR.

fix: Fallback to defaults if base URL is not supplied.

---

examples/salty-ocean-model-comparison/src/index.tsx
packages/gensx-openai/src/openai.tsx
packages/gensx-openai/tests/index.test.tsx

If you're using OpenAI as a provider with the default client setup, you shouldn't have to wrap your OpenAIChatCompletions in an OpenAIProvider. I.e. 
``` 
<ChatCompletion
model="gpt-4o-mini"
temperature={0.5}
messages={[
{ role: "system", content: systemPrompt },
{ role: "user", content: prompt },
]}
response_format={{ type: "json_object" }} / >
</ChatCompletion>
```
instead of
```
<OpenAIProvider apiKey={process.env.OPENAI_API_KEY}>
<ChatCompletion
model="gpt-4o-mini"
temperature={0.5}
messages={[
{ role: "system", content: systemPrompt },
{ role: "user", content: prompt },
]}
response_format={{ type: "json_object" }} / >
</ChatCompletion>
</OpenAIProvider>
```

feat: add default client for openai package

---

packages/gensx/src/utils/bundler.ts

ensuring that docker runs with the platform as linux/amd64

fix: adding platform to docker build command

---

examples/chat-memory/src/workflows.tsx
packages/gensx-storage/src/blob/provider.tsx
packages/gensx-storage/src/blob/remote.ts
packages/gensx-storage/src/blob/types.ts
packages/gensx-storage/tests/provider.test.tsx
packages/gensx-storage/tests/remote.test.ts

- Make `kind` optional on BlobProvider. It defaults to "filesystem" if not provided unless process.env.GENSX_RUNTIME="cloud" in which case it defaults to "cloud".
- Also fixes a bug where getJson() wasn't properly parsing the json
- Adds tests for both

feat: make kind optional and fix getJson

---

packages/gensx-core/src/checkpoint.ts

Use the `traces` API for creating traces. This uses the new model of `POST`/`PUT`.

feat: Migrate to use the traces API.

---

packages/gensx-claude-md/tsconfig.build.json
packages/gensx-cline-rules/tsconfig.build.json
packages/gensx-cursor-rules/tsconfig.build.json
packages/gensx-openai/package.json
packages/gensx-windsurf-rules/tsconfig.build.json
turbo.json

The `repository` field got dropped from the `@gensx/openai` package.json somehow, so the publish is failing.

chore: Fix repository that went missing from package.json

---

containers/builder/build.sh
packages/gensx/src/utils/bundler.ts
pnpm-lock.yaml

Bundling is not compatible with @libsql/client, so work around it in the bundler by installing the package and specifying the correct native dependency.
https://github.com/tursodatabase/libsql-client-ts/issues/112

fix: Fix bundling of storage package.

---

packages/gensx/src/utils/bundler.ts

Updating docker command to always pull the latest if you don't have it. This fixes an issue where you currently need to manually pull the latest docker image to update it.

fix: update docker command to always pull latest image

---

packages/gensx/src/index.ts
packages/gensx/src/utils/user-agent.ts

Remove JSON imports, and instead read the file to extract the version. This is to remove a warning about json imports.

fix: Don't import json so that there is no warning.

---

examples/rag/README.md
examples/rag/src/data-ingestion.tsx
examples/rag/src/index.tsx
examples/rag/src/workflows.tsx
examples/text-to-sql/README.md
examples/text-to-sql/src/data-ingestion.tsx
examples/text-to-sql/src/index.tsx
examples/text-to-sql/src/workflows.tsx
packages/gensx-storage/src/blob/blobClient.ts
packages/gensx-storage/src/blob/filesystem.ts
packages/gensx-storage/src/blob/remote.ts
packages/gensx-storage/src/blob/types.ts
packages/gensx-storage/src/database/databaseClient.ts
packages/gensx-storage/src/index.ts
packages/gensx-storage/src/search/provider.tsx
packages/gensx-storage/src/search/remote.ts
packages/gensx-storage/src/search/searchClient.ts
packages/gensx-storage/src/search/types.ts
packages/gensx-storage/tests/search/index.test.tsx
packages/gensx-storage/tests/search/provider.test.tsx

- Adding a `BlobClient`, `DatabaseClient`, and `SearchClient` that allow users to interact with storage without needing to use JSX.
- Updates the RAG and text-to-sql examples to use the new storage clients.
- Removed support for defaulPrefix in search and added a couple of control plane operations for blob for consistency.

feat: adding native ts/js support for storage APIs

---

packages/gensx/src/commands/start.ts
packages/gensx/src/index.ts
website/docs/src/content/cli-reference/start.mdx

adds a `--port` param to override the default port of `1337`
Fixes #598

feat: adding port option to dev server

---

examples/salty-ocean-model-comparison/src/index.tsx
packages/gensx-openai/src/openai.tsx
packages/gensx-openai/src/structured-output.tsx

Prevent throwing an error if there is not an `OPENAI_API_KEY` in the environment.
I wasn't able to figure out a good way to test this, as there is no way for me to clear the environment before the import happens.
Fixes #601

fix: Only instantiate default OpenAI client if there is an OPENAI_API_KEY.

---

packages/gensx-vercel-ai-sdk/tests/index.test.tsx

The DALL-E test fairly regularly times out at 30 seconds. Going ahead and commenting it out for now. Should make tests a lot faster and save us a few dollars a week.
Also upgraded to `gpt-4.1-nano` so chat tests will be even cheaper.

chore: removing flakey dall-e test

---

packages/gensx/src/commands/run.ts

Removes "input" wrapper from run command for both start/run API calls

fix: removing input wrapper from run command

---

packages/gensx/src/commands/deploy.ts

Use buildId from the response instead of deploymentId.
Fix the issue where there is no deployment ID for the link after deploys.

fix: Use buildId instead of deploymentId.

---

packages/gensx/src/dev-server.ts
packages/gensx/tests/dev-server.test.ts

- Removes "input" from top level of request input for starting/running workflow
- Removing response envelope from all API calls
- Making the start API return a 202 rather than 200 on successful starts
- Throwing a 422 rather than a 500 when a workflow itself fails
- Fixing response body of getExecutionStatus to show error in logs.stderr

feat: updating dev server to be at parity with prod APIs

---

packages/gensx-core/src/checkpoint.ts

fix: fixing the execution trace url that's printed

---

packages/gensx/src/commands/run.ts
packages/gensx/src/index.ts

- Fixes bug when running workflows with no inputs. Before you had to specify `--input '{}'`. With this, that is no longer necessary
- Fixes bug where environment wasn't properly wired up in the run command

fix: fixing env in run command and allowing empty inputs

---

website/home/components/nav.tsx

There exists a bug on mobile (narrow screen widths) views on the navigation menu.
Remove duplicate Docs link from the social links area of the navigation menu.
Thanks for the presentation at Ai.js event

docs: remove duplicate "Docs" links on the navigation menu

---

.github/workflows/release-cli-binary.yml

Attempting to fix `line 2: deno: command not found` error

fix: updating release cli pipeline to fix deno error

---

packages/gensx-storage/src/search/remote.ts
packages/gensx-storage/src/search/searchClient.ts
packages/gensx-storage/src/search/types.ts
packages/gensx-storage/tests/search/index.test.tsx

updates listNamespaces to return an object instead of strings. aligns this with other storage list APIs and future proofs.
Also fixes a bug where the listNamespaces url wasn't correct and makes props not required for `SearchClient`

feat: updating listNamespaces to return an object

---

packages/gensx/src/utils/user-agent.ts

adding try/catch so that the version will just be unset if package.json can't be found. this will fix errors with using gensx via homebrew.

fix: making user agent logic permissive

---

examples/blog-writer/package.json
examples/chat-memory/package.json
examples/deep-research/package.json
examples/hacker-news-analyzer/package.json
examples/rag/package.json
examples/text-to-sql/package.json
packages/gensx/src/index.ts
packages/gensx/src/templates/projects/typescript/package.json.template
website/docs/src/content/cli-reference/deploy.mdx
website/docs/src/content/cli-reference/run.mdx
website/docs/src/content/cloud/projects-environments.mdx
website/docs/src/content/cloud/serverless-deployments.mdx
website/docs/src/content/quickstart.mdx

We need to remove `-ev` because it causes an error when using the gensx cli via homebrew. 
Given `--env` is already short, we opted to remove `-ev` and make `-e` mean envVar rather than environment name.

fix: removing -ev cli option in favor of -e

---

packages/gensx/src/commands/deploy.tsx
packages/gensx/src/commands/login.tsx
packages/gensx/src/components/EnvironmentResolver.tsx
packages/gensx/src/hooks/useProjectName.ts
packages/gensx/src/models/environment.ts
packages/gensx/tests/commands/deploy.test.ts
packages/gensx/tests/components/EnvironmentResolver.test.ts

The ink migration introduced a bug where projects couldn't be deployed if the project did not already exist. This PR fixes that bug and does some other minor cleanup

fix: resolves bug preventing deployment if project doesn't exist

---

release-please-config.json

Removes hardcoded package versions for core, anthropic, openai, and vercel.
However, the storage package didn't get the proper version bump because it was missing the `release-as`

feat: upgrade storage package version

---

packages/gensx-core/src/context.ts
packages/gensx-core/src/workflow-context.ts
packages/gensx-core/tests/progress.test.ts

This PR makes emit progress more flexible. All data will now be returned nested under the `data` object and can be nested however you want. also makes it so you can use values other than just strings.
You can now stream complex objects like this:
```
{
"id": "1749747362972-0",
"timestamp": "2025-06-12T16:56:02.978Z",
"type": "progress",
"data": {
"step": 6,
"action": "workflow_completed",
"status": "success",
"summary": {
"threadId": "667",
"totalMessages": 2,
"conversation": {
"turns": 1,
"lastUserInput": "write a poem!",
"responseGenerated": true,
"persistedToStorage": true
},
"metadata": {
"timestamp": "2025-06-12T16:56:02.970Z",
"model": "gpt-4.1-mini",
"performance": {
"totalSteps": 6,
"storageOperations": 2,
"apiCalls": 1
},
...
```

feat: updating emitProgress to support nested objects

---

packages/gensx-core/package.json
packages/gensx-core/src/component.ts
packages/gensx-core/src/context.ts
packages/gensx-core/src/index.ts
packages/gensx-core/src/workflow-context.ts
packages/gensx-core/src/workflow-state.ts
packages/gensx-core/tests/workflow-state.test.ts
pnpm-lock.yaml

* change `emitProgress` to `publishData`
* add `publishEvent` to publish arbitrary events with a given label.
* add `publishObject` to publish arbitrary objects with a given label.
* add `createEventStream` as a helper for creating a strongly typed event emitter
* add `createObjectStream` as a helper for creating a strongly typed state emitter
Things to call out:
* I opted not to use JSON patch or some sort of updating mechanism for transmitting state changes. That would make the stream a stateful thing (must process the whole thing when reconnecting), and I don't want to necessarily make that required yet.
* `emitProgress` becomes a bit of a second class citizen with its new name, and I think that is the right place for it. It is fully-flexible, but not really the happy path that we will …

feat: Add helpers for event stream and state.

---

packages/gensx/src/commands/project/create.tsx
packages/gensx/src/commands/project/list.tsx
packages/gensx/src/commands/project/show.tsx
packages/gensx/src/index.ts
packages/gensx/src/models/workflows.ts
packages/gensx/tests/commands/project/create.test.ts
packages/gensx/tests/commands/project/list.test.ts
packages/gensx/tests/commands/project/show.test.ts
website/docs/src/content/cli-reference/_meta.ts
website/docs/src/content/cli-reference/index.mdx
website/docs/src/content/cli-reference/project/_meta.ts
website/docs/src/content/cli-reference/project/create.mdx
website/docs/src/content/cli-reference/project/ls.mdx
website/docs/src/content/cli-reference/project/show.mdx

Adds CLI commands for projects:
- `gensx project` - shows the current project. includes details on existing envs and workflows
- `gensx project create` - create a project
- `gensx project ls` - lists projects for the org
https://github.com/user-attachments/assets/5c852c7b-3473-47af-a961-74f85d91a012
Fixes #782

feat: adding project cli commands

---

packages/gensx-core/src/checkpoint-types.ts
packages/gensx-core/src/checkpoint.ts
packages/gensx-core/src/component.ts
packages/gensx-core/src/context.ts
packages/gensx-core/src/index.ts
packages/gensx-core/src/restore-checkpoint.ts
packages/gensx-core/src/wait-for-input.ts
packages/gensx-core/src/workflow-context.ts
packages/gensx-core/tests/checkpoint.test.ts
packages/gensx-core/tests/replay.test.ts
packages/gensx-core/tests/restore-checkpoint.test.ts
packages/gensx-core/tests/sequence-number-replay.test.ts
packages/gensx-core/tests/utils/executeWithCheckpoints.ts
packages/gensx-core/tests/wait-for-input.test.ts
packages/gensx-core/tests/workflow-context.test.ts

Support restoring a prior checkpoint and restarting workflow execution from that point, including feedback from "the future".
```ts
export const ComponentWithCheckpoint = gensx.Component("ComponentWithCheckpoint", async ({ input }: Props) => {
const { feedback, restore } = gensx.createCheckpoint();
gensx.publishData(`Got feedback: ${feedback}`);
// Wait for feedback from the user
const result = await gensx.waitForInput<{ data: string }>(
async (callbackUrl) => {
gensx.publishData(callbackUrl);
await setTimeout(1000);
},
);
gensx.publishData(`Got result from external system: '${result.data}'`);
// If the user does not approve, restore the checkpoint and include the feedback from the user.
if (result.data.includes("error")) {
gensx.publishData("Restoring from checkpoint");
await …
```

feat: Checkpoint restoration

---

packages/gensx/src/commands/run.tsx
packages/gensx/src/index.ts

```
$ gensx run -i '{ "input": "hello" }' NoOpWorkflow -y --progress
Streaming progress events:
Workflow started: NoOpWorkflow
Data: "Starting workflow"
Data: "1. null 2. null"
Workflow started: NoOpWorkflow
Data: "Starting workflow"
Data: "1. null 2. null"
```

feat: Add --progress CLI param for run command to stream the progress events after calling start.

---

packages/gensx-client/src/index.ts

removing default export since we already have a standard export above

fix: remove duplicate export from gensx/client

---

packages/gensx/src/commands/deploy.tsx

Changed dashboard URL to match console from:
/{org}/{project}/{environment}/workflows?deploymentId={buildId}
To:
/{org}/{project}?env={environmentId}

fix: update dashboard URL format to use env query parameter

---

packages/gensx-react/src/hooks/use-gensx.ts

Making the type for `useObject` more flexible to match the update made [here](https://github.com/gensx-inc/gensx/pull/791/files#diff-bb542a52ce30475038b7567974245f80be037dc7b91914c414c2df05eeb4dd60). 
Turns out our `JsonValue` type is a bit precarious. Currently many types don't truly align with `JsonValue`. For example, with the following type 
```
export interface SearchResult  {
title: string;
url: string;
description: string;
relevanceScore?: number;
content?: string;
}
```
We get an error when using it with useObject:
```
const workflowSearchResults = useObject<SearchResult[]>( //SearchResult also causes an err
execution,
"searchResults",
);
```
Here's o3's summary of why: JsonValue includes a { [key: string]: JsonValue } index signature, which statically guarantees that every …

fix: make types for useObject more flexible

---

examples/text-to-sql/package.json
packages/gensx-storage/README.md
packages/gensx-storage/package.json
packages/gensx-storage/src/database/databaseClient.ts
packages/gensx-storage/src/database/filesystem.ts
packages/gensx-storage/src/database/remote.ts
packages/gensx-storage/src/database/types.ts
pnpm-lock.yaml

- make libsql an optional peer dependency
- load libsql dynamically for filesystem databases
- update docs for optional installation and Next.js config
fixes #788

fix: make @libsql/client optional in @gensx/storage

---

website/home/components/footer.tsx

The github footer link was a placeholder - updated with actual link.

fix: footer github link
